---
# tasks file for signal-cli-rest-api

- name: copy docker compose stack
  ansible.builtin.copy:
    src: defaults/signal-cli-rest-api
    dest: /opt/containers
    mode: '644'
    force: true

- name: copy .env.j2
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /opt/containers/signal-cli-rest-api/.env
    mode: '644'

- name: start docker compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/containers/signal-cli-rest-api
    state: present
