services:

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      WATCHTOWER_SCHEDULE: 0 0 3 * * * # check daily at 03:00 o'clock
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATION_REPORT: true
      WATCHTOWER_NO_STARTUP_MESSAGE: true
    env_file:
      - /opt/containers/env_files/email.env
      - .env
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
