---
x-shared:
  resticker-service: &resticker-service
    image: mazzolino/restic
    hostname: ${HOSTNAME}
    restart: unless-stopped
    volumes:
      - ./rclone.conf:/run/secrets/rclone.conf:ro
    env_file:
      - .env

services:
  backup:
    <<: *resticker-service
    environment:
      BACKUP_CRON: "0 */30 0-2,6-23 * * *"
      SKIP_INIT: "false"
      RESTIC_BACKUP_ARGS: >-
        --tag containers,volumes
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
    volumes:
      - ./rclone.conf:/run/secrets/rclone.conf:ro
      - /opt/containers:/data/containers
      - /var/lib/docker/volumes:/data/volumes
  prune:
    <<: *resticker-service
    environment:
      PRUNE_CRON: "0 0 4 * * *"
  check:
    <<: *resticker-service
    environment:
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
