- name: Get the list of enabled apps
  ansible.builtin.command: docker exec --user www-data nextcloud php occ app:list --enabled
  register: enabled_apps_output
  changed_when: False

- name: Set fact for enabled apps
  set_fact:
    enabled_apps: "{{ enabled_apps_output.stdout | regex_findall('  - (.+?):') }}"

- name: Disable apps not in the desired list
  ansible.builtin.command: docker exec --user www-data nextcloud php occ app:disable {{ item }}
  loop: "{{ enabled_apps }}"
  when: item not in NEXTCLOUD_DESIRED_ENABLED_APPS
  register: app_status
  changed_when: "'disabled' in app_status.stdout"
  failed_when: "'disabled' not in app_status.stdout"

- name: Enable desired apps that are not currently enabled
  ansible.builtin.command: docker exec --user www-data nextcloud php occ app:enable {{ item }}
  loop: "{{ NEXTCLOUD_DESIRED_ENABLED_APPS }}"
  when: item not in enabled_apps
  ignore_errors: true
  register: app_status
  changed_when: "'enabled' in app_status.stdout and 'already' not in app_status.stdout"
  failed_when: "'enabled' not in app_status.stdout"
