- name: Get the list of existing groups
  ansible.builtin.command: docker exec --user www-data nextcloud php occ group:list
  register: existing_groups_output
  changed_when: False

- name: Set fact for existing groups
  set_fact:
    existing_groups: "{{ existing_groups_output.stdout | regex_findall('  - (.+?):') }}"

- name: Ensure desired groups exist
  ansible.builtin.command: docker exec --user www-data nextcloud php occ group:add {{ item | regex_replace(' ', '\\ ') }}
  loop: "{{ NEXTCLOUD_DESIRED_GROUPS }}"
  when: item not in existing_groups
  ignore_errors: true
  register: group_status
  changed_when: "'Created group ' in group_status.stdout"
