---

services:
  zammad-resticker:
    image: mazzolino/restic
    container_name: zammad-resticker
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      BACKUP_CRON: "0 */30 0-2,6-23 * * *"
      RESTIC_BACKUP_SOURCES: /data/zammad-postgresql-data/zammad_production.pg_dump
      RESTIC_BACKUP_ARGS: >-
        --tag zammad
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      PRE_COMMANDS: |-
            docker exec zammad-railsserver bundle exec rails r 'Channel.where(area: "Email::Account").update_all(active: false)'
            docker exec zammad-postgresql pg_dump --file=/var/lib/postgresql/data/zammad_production.pg_dump --dbname=zammad_production --username=zammad
            docker exec zammad-railsserver bundle exec rails r 'Channel.where(area: "Email::Account").update_all(active: true)'
    env_file:
      - /opt/containers/resticker/.env
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/containers/resticker/rclone.conf:/run/secrets/rclone.conf:ro
      - postgresql-data:/data/zammad-postgresql-data
    depends_on:
      zammad-railsserver:
        condition: service_healthy
      zammad-postgresql:
        condition: service_healthy
  zammad-backup:
    container_name: zammad-backup
    profiles:
      - do-not-start
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_BACKUP_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_BACKUP_RESOURCES_LIMITS_MEMORY:-500m}"
  zammad-elasticsearch:
    container_name: zammad-elasticsearch
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_ELASTICSEARCH_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_ELASTICSEARCH_RESOURCES_LIMITS_MEMORY:-1G}"
  zammad-init:
    container_name: zammad-init
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_INIT_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_INIT_RESOURCES_LIMITS_MEMORY:-500M}"
  zammad-memcached:
    container_name: zammad-memcached
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_MEMCACHED_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_MEMCACHED_RESOURCES_LIMITS_MEMORY:-500M}"
  zammad-nginx:
    container_name: zammad-nginx
    ports: !reset []
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.zammad-secure.entrypoints: websecure
      traefik.http.routers.zammad-secure.middlewares: default@file
      traefik.http.routers.zammad-secure.rule: Host(`${ZAMMAD_FQDN}`)
      traefik.http.routers.zammad-secure.service: zammad
      traefik.http.routers.zammad-secure.tls: "true"
      traefik.http.routers.zammad-secure.tls.certresolver: http_resolver
      traefik.http.routers.zammad.entrypoints: web
      traefik.http.routers.zammad.rule: Host(`${ZAMMAD_FQDN}`)
      traefik.http.services.zammad.loadbalancer.server.port: "8080"
    networks:
      default: null
      proxy: null
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_NGINX_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_NGINX_RESOURCES_LIMITS_MEMORY:-500M}"
  zammad-postgresql:
    container_name: zammad-postgresql
    image: pgautoupgrade/pgautoupgrade:${POSTGRES_VERSION:-17.10-alpine}
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_POSTGRESQL_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_POSTGRESQL_RESOURCES_LIMITS_MEMORY:-500M}"
  zammad-railsserver:
    container_name: zammad-railsserver
    environment:
      RAILS_TRUSTED_PROXIES: ${RAILS_TRUSTED_PROXIES:-nginx-proxy-manager}
    volumes:
      - ./app/models/ticket.rb:/opt/zammad/app/models/ticket.rb
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_RAILSSERVER_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_RAILSSERVER_RESOURCES_LIMITS_MEMORY:-500M}"
  zammad-redis:
    container_name: zammad-redis
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_REDIS_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_REDIS_RESOURCES_LIMITS_MEMORY:-500M}"
  zammad-scheduler:
    container_name: zammad-scheduler
    volumes:
      - ./app/models/ticket.rb:/opt/zammad/app/models/ticket.rb
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_SCHEDULER_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_SCHEDULER_RESOURCES_LIMITS_MEMORY:-500M}"
  zammad-websocket:
    container_name: zammad-websocket
    deploy:
      resources:
        limits:
          cpus: "${ZAMMAD_WEBSOCKET_RESOURCES_LIMITS_CPUS:-1.0}"
          memory: "${ZAMMAD_WEBSOCKET_RESOURCES_LIMITS_MEMORY:-500M}"

networks:
  default:
  proxy:
    external: true
