---
- name: deploy it infrastructure servers
  hosts: unstable
  remote_user: root

  pre_tasks:

    - name: Ensure a locale exists
      community.general.locale_gen:
        name: '{{ item }}'
      with_items:
        - en_US.UTF-8
        - de_DE.UTF-8

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ ansible_host }}"

    - name: import ssh keys for root
      # https://stackoverflow.com/a/48882051
      ansible.posix.authorized_key:
        user: root
        key: https://github.com/{{ item }}.keys
        comment: '{{ item }}'
      ignore_errors: yes
      with_items:
        - igami
        - leon2225
        - mattn81
        - bongald
        - stikkx
        - ReneHezser

  roles:

    - role: weareinteractive.apt
      vars: 
        apt_upgrade: dist
        apt_unattended_upgrades_automatic_reboot: yes
        apt_unattended_upgrades_automatic_reboot_time: 02:00

    - role: nickjj.docker

    - role: roles/traefik-crowdsec-stack
      vars:
        # Service Traefik
        SERVICES_TRAEFIK_IMAGE_VERSION: latest
        SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST: "`traefik.{{ ansible_host }}`"
        SERVICES_TRAEFIK_CERTIFICATESRESOLVERS_EMAIL: cyber@makerspace-gt.de
