---
- name: deploy it infrastructure servers on this container
  # 'all' doesn't include localhost. Need to specify it. 
  hosts: localhost
  # Need sudo, e.g. for accessing /etc/locale.gen for the first task
  become: true

  pre_tasks:

    - name: Ensure a locale exists
      community.general.locale_gen:
        name: '{{ item }}'
      with_items:
        - en_US.UTF-8
        - de_DE.UTF-8

    - name: Set timezone to Europe/Berlin
      community.general.timezone:
        name: Europe/Berlin

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ ansible_host }}"

    # Disabled as we're running on this machine, and ssh'ed into it already
    # - name: import ssh keys for root

    - name: Ensure /opt/containers/env_files directory exists
      ansible.builtin.file:
        path: /opt/containers/env_files
        state: directory
        mode: '0755'

    - name: copy email.env
      ansible.builtin.copy:
        src: defaults/opt/containers/env_files/dev_email.env
        dest: /opt/containers/env_files/email.env

    # Shouldn't this happen as part of the respective role?
    # If not, a workaround with a virtual env used by the whole playbook:
    # https://medium.com/@crobin/ansible-module-dependency-management-d2f5235aa75a
    - name: install python-packages needed by roles
      ansible.builtin.pip:
        # required by zammad
        name: requests

  roles:

    - role: weareinteractive.apt
      vars: 
        apt_upgrade: dist
        apt_unattended_upgrades_automatic_reboot: yes
        apt_unattended_upgrades_automatic_reboot_time: 02:00

    # Docker is installed on the machine this is running on
    # via the devcontainer-feature - as this playbook runs _here_
    # For future reference: this image (devcontainer-python) like
    # all other such images doesn't run systemd - official message:
    # "systemd" is not running in this container due to its overhead.
    # Use the "service" command to start services instead. e.g.:
    # service --status-all

    # - role: nickjj.docker

    - role: roles/watchtower

    - role: roles/traefik-crowdsec-stack
      vars:
        # Service Traefik
        SERVICES_TRAEFIK_IMAGE_VERSION: latest
        SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST: "`traefik.{{ ansible_host }}`"
        SERVICES_TRAEFIK_CERTIFICATESRESOLVERS_EMAIL: cyber@dev.makerspace-gt.de

    - role: roles/zammad-stack
      vars:
        SERVICES_ZAMMAD_LABELS_TRAEFIK_HOST: "`helpdesk.dev.makerspace-gt.de`"

    - role: roles/vaultwarden
      vars:
        SERVICES_VAULTWARDEN_ENVIRONMENT_DOMAIN: "vault.dev.makerspace-gt.de"

    - role: roles/nextcloud-stack
      vars:
        NEXTCLOUD_OCC_COMMANDS:
        - config:system:set overwriteprotocol --value="https"
        - config:system:set maintenance_window_start --type=integer --value=1
        - db:add-missing-indices
        - config:system:set default_language --value="de"
        - config:system:set default_locale --value="de_DE"
        - config:system:set default_phone_region --value="DE"
        - config:system:set default_timezone --value="Europe/Berlin"
        - config:system:set upgrade.disable-web --type boolean --value true
        - config:system:set simpleSignUpLink.shown --type boolean --value false
        - config:system:set trusted_domains 1 --value={{ NEXTCLOUD_HOSTNAME }}
        - config:app:set dav generateBirthdayCalendar --value="no"
        - config:app:set registration admin_approval_required --value="yes"
        - config:app:set registration registered_user_group --value="makerspace-gt"
        - group:adduser makerspace-gt makerspace-gt
        - user:setting makerspace-gt settings email cyber@dev.makerspace-gt.de
        NEXTCLOUD_DESIRED_GROUPFOLDERS:
          - name: Vorstand
            groups:
              - Vorstand: read write share delete
          - name: Bilder
            groups:
              - makerspace-gt: read write share delete
          - name: home
            groups:
            - makerspace-gt: read write share delete
          - name: hub
            groups:
            - makerspace-gt: read write share delete
          - name: Projekte
            groups:
            - makerspace-gt: read write share delete
          - name: Social Media
            groups:
            - Social Media: read write share delete
        NEXTCLOUD_HOSTNAME: "cloud.dev.makerspace-gt.de"
        NEXTCLOUD_DESIRED_GROUPS:
          - Vorstand
          - makerspace-gt
          - Social Media
        NEXTCLOUD_DESIRED_ENABLED_APPS:
          - calendar
          - calendar_resource_management
          - cloud_federation_api
          - comments
          - contactsinteraction
          - dav
          - federatedfilesharing
          - federation
          - files
          - files_downloadlimit
          - files_pdfviewer
          - files_reminders
          - files_sharing
          - files_trashbin
          - files_versions
          - groupfolders
          - logreader
          - lookup_server_connector
          - notifications
          - oauth2
          - photos
          - previewgenerator
          - privacy
          - provisioning_api
          - registration
          - serverinfo
          - settings
          - sharebymail
          - systemtags
          - text
          - theming
          - twofactor_backupcodes
          - updatenotification
          - viewer
          - workflowengine

    - role: roles/vikunja-stack
      vars:
        SERVICES_LABELS_TRAEFIK_HOST: "todo.dev.makerspace-gt.de"

    - role: roles/wikijs-stack
      vars:
        SERVICES_WIKIJS_LABELS_TRAEFIK_HOST: "`wiki.dev.makerspace-gt.de`"

    - role: roles/resticker-stack
