---
- name: deploy it infrastructure servers
  hosts: unseven
  remote_user: root

  roles:

    - role: roles/zammad
      vars:
        SERVICES_ZAMMAD_LABELS_TRAEFIK_HOST: helpdesk.makerspace-gt.de
