- name: Ensure directory exists
  ansible.builtin.file:
    path: /opt/containers/watchtower
    state: directory
    mode: "0755"

- name: copy docker compose stack
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/containers/watchtower/docker-compose.yml
    mode: "644"

- name: copy .env.j2
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /opt/containers/watchtower/.env
    mode: "644"

- name: start docker compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/containers/watchtower
    state: present
