- name: copy docker compose stack
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/containers/watchtower/docker-compose.yml
    mode: '644'
    force: true

- name: copy .env.j2
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /opt/containers/watchtower/.env
    mode: '644'

- name: start docker compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/containers/watchtower
    state: present
