---
# tasks file for zammad-stack

- name: Create zammad-backup volume
  community.docker.docker_volume:
    name: zammad-backup

- name: copy docker compose stack
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/containers/zammad-stack/docker-compose.yml
    mode: '644'
    force: true

- name: copy .env.j2
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /opt/containers/zammad-stack/.env
    mode: '644'

- name: Setting vm.max_map_count for Elasticsearch
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    # state: present
    sysctl_set: yes
    # sysctl_file: "/etc/sysctl.conf"
    # reload: true
    # ignoreerrors: false

- name: start docker compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/containers/zammad-stack
    state: present
