---
# tasks file for resticker

- name: copy docker compose
  ansible.builtin.copy:
    src: defaults/resticker
    dest: /opt/containers
    mode: '644'
    force: true

- name: copy .env.j2
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /opt/containers/resticker/.env
    mode: '644'

- name: start docker compose
  community.docker.docker_compose_v2:
    project_src: /opt/containers/resticker
    state: present
    remove_orphans: true
