---
- name: create app/models directory
  ansible.builtin.file:
    path: /opt/containers/zammad/app/models
    state: directory
    mode: '755'

- name: copy static files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/containers/zammad/{{ item }}"
    mode: '644'
  loop:
    - app/models/ticket.rb

- name: Setting vm.max_map_count for Elasticsearch
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes

- name: Setting vm.overcommit_memory for Redis
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    sysctl_set: yes

- ansible.builtin.set_fact:
    compose_name: "{{ role_path | basename }}"

- ansible.builtin.include_role:
    name: compose_deploy

- name: restore zammad
  ansible.builtin.include_tasks:
    file: restore.yaml
    apply:
      tags: [zammad-restore, never]
  tags: [zammad-restore, never]

- name: decommission zammad
  ansible.builtin.include_tasks:
    file: decommission.yaml
    apply:
      tags: [zammad-decommission, never]
  tags: [zammad-decommission, never]
