# https://github.com/dani-garcia/vaultwarden

version: "3.5"

services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: "vaultwarden"
    restart: always
    labels:
      # https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_HOST}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=myresolver"
    environment:
      - "DOMAIN=https://${VAULTWARDEN_HOST}"
      - "WEBSOCKET_ENABLED=true"
    volumes:
      - ./data:/data
    networks:
      - web

networks:
  web:
    driver: overlay
    external: true
