SERVICES_LABELS_TRAEFIK_HOST: "vikunja.{{ ansible_host }}"

VIKUNJA_LEGAL_IMPRINTURL: https://makerspace-gt.de/impressum/

VIKUNJA_SERVICE_JWTSECRET: "{{ vault_VIKUNJA_SERVICE_JWTSECRET | default(omit) }}"

VIKUNJA_MAILER_ENABLED: true
VIKUNJA_MAILER_HOST: "{{ SMTP_HOST }}"
VIKUNJA_MAILER_PORT: "{{ SMTP_PORT }}"
VIKUNJA_MAILER_AUTHTYPE: login
VIKUNJA_MAILER_USERNAME: "{{ SMTP_USERNAME }}"
VIKUNJA_MAILER_PASSWORD: "{{ SMTP_PASSWORD }}"
VIKUNJA_MAILER_FROMEMAIL: "{{ SMTP_SENDER }}"
VIKUNJA_MAILER_FORCESSL: true
