apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja-release
  namespace: vikunja
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: truecharts/vikunja
      reconcileStrategy: ChartVersion
      interval: 1m0s
      sourceRef:
        kind: HelmRepository
        name: truecharts
  values:
