# https://github.com/zammad/zammad-docker-compose/blob/master/.examples/proxy/docker-compose.proxy-example.yml

---
version: '3'

services:

  zammad-nginx:
    environment:
      - VIRTUAL_HOST=${ZAMMAD_HOST}
      - NGINX_SERVER_SCHEME=https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zammad.rule=Host(`${ZAMMAD_HOST}`)"
      - "traefik.http.routers.zammad.entrypoints=websecure"
      - "traefik.http.routers.zammad.tls.certresolver=myresolver"
    networks:
      - default
      - web

  zammad-railsserver:
    volumes:
      - zammad-data:/opt/zammad
      - ./application.rb:/opt/zammad/config/application.rb:ro

networks:
  web:
    driver: overlay
    external: true

volumes:
  zammad-data:
    driver: local
