version: "3.3"

services:

  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
     - 'postgresql-keycloak:/bitnami/postgresql'

  keycloak:
    image: bitnami/keycloak:latest
    depends_on:
      - postgresql
    container_name: keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.igami.makerspace-gt.de`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - web

networks:
  web:
    driver: overlay
    external: true

volumes:
  postgresql-keycloak:
    driver: local