services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - vaultwarden-data:/data/
    environment:
      WEBSOCKET_ENABLED: "true" ## Enables websocket notifications
      DOMAIN: "https://${SERVICES_VAULTWARDEN_LABELS_TRAEFIK_HOST}" # It's recommended to configure this value, otherwise certain functionality might not work, like attachment downloads, email links and U2F.
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.vaultwarden-secure.entrypoints: websecure
      traefik.http.routers.vaultwarden-secure.middlewares: default@file
      traefik.http.routers.vaultwarden-secure.rule: Host(${SERVICES_VAULTWARDEN_LABELS_TRAEFIK_HOST})
      traefik.http.routers.vaultwarden-secure.service: vaultwarden
      traefik.http.routers.vaultwarden-secure.tls: "true"
      traefik.http.routers.vaultwarden-secure.tls.certresolver: http_resolver
      traefik.http.routers.vaultwarden.entrypoints: web
      traefik.http.routers.vaultwarden.rule: Host(${SERVICES_VAULTWARDEN_LABELS_TRAEFIK_HOST})
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"
    networks:
      default: null
      proxy: null

networks:
  default:
  proxy:
    external: true

volumes:
  vaultwarden-data:
    driver: local
