- name: Configure machines
  hosts: all
  become: true

  tasks:
    - name: Download and install RKE2
      shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{ rke2_version }} sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Install Flux CLI
      shell: |
        curl -s https://fluxcd.io/install.sh | bash
      args:
        executable: /bin/bash

    - name: Install Kubernetes CLI
      ansible.builtin.shell:
        cmd: sudo apt-get install -y kubectl
