_version: 2
maker:
  active: true
  apikey: null
  groups:
  - admins
  - users
  password: $argon2id$v=19$m=65536,t=3,p=4$S+m9d65VypkTwljLWQshJA$x81OG17D11KcUoetX00kyZx/9Ues0RjiN8BuWhKBxfA
  permissions: []
  roles:
  - user
  - admin
  settings: {}
