# - name: Converge
#   hosts: all
#   gather_facts: false
#   tasks:
#     - name: Replace this task with one that validates your content
#       ansible.builtin.debug:
#         msg: "This is the effective test"
---
- name: Include your playbook
  ansible.builtin.import_playbook: ../../playbooks/test.yml
