---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:bookworm
    pre_build_image: true
    memory: "4096m"
    cpus: 4
    command: ""
    # Enable systemd, also needs this filesystem to work
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc:/etc
      - /run:/run
    privileged: true
    systemd: true
    user: root
provisioner:
  name: ansible
  options:
    vvv: true
  env:
    ANSIBLE_ROLES_PATH: ../../roles/:/home/vscode/.ansible/roles//
verifier:
  name: ansible
