apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-recurring-backup-job
  namespace: longhorn-system
spec:
  task: system-backup
  # At minute 0 every hour
  cron: '0 * * * *'
  retain: 3
  parameters:
    volume-backup-policy: if-not-present
