---
# tasks file for vaultwarden

- name: Create vaultwarden volume
  community.docker.docker_volume:
    name: vaultwarden-data

- name: copy docker compose stack
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/containers/vaultwarden/docker-compose.yml
    mode: '644'
    force: true

- name: copy .env.j2
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /opt/containers/vaultwarden/.env
    mode: '644'

- name: start docker compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/containers/vaultwarden
    state: present
