---
# defaults file for zammad-stack

ELASTICSEARCH_VERSION: latest
MEMCACHE_VERSION: latest
POSTGRES_IMAGE: pgautoupgrade/pgautoupgrade
POSTGRES_VERSION: latest
REDIS_VERSION: latest
VERSION: latest
SERVICES_ZAMMAD_LABELS_TRAEFIK_HOST: "`zammad.{{ ansible_host }}`"
