---
services:
  zammad-backup:
    image: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
    labels:
      com.centurylinklabs.watchtower.enable: true

  zammad-elasticsearch:
    labels:
      com.centurylinklabs.watchtower.enable: true

  zammad-init:
    labels:
      com.centurylinklabs.watchtower.enable: true

  zammad-memcached:
    labels:
      com.centurylinklabs.watchtower.enable: true
  zammad-nginx:
    environment:
      NGINX_SERVER_SCHEME: "https"
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.zammad-secure.entrypoints: websecure
      traefik.http.routers.zammad-secure.middlewares: default@file
      traefik.http.routers.zammad-secure.rule: Host(${SERVICES_ZAMMAD_LABELS_TRAEFIK_HOST})
      traefik.http.routers.zammad-secure.service: zammad
      traefik.http.routers.zammad-secure.tls: "true"
      traefik.http.routers.zammad-secure.tls.certresolver: http_resolver
      traefik.http.routers.zammad.entrypoints: web
      traefik.http.routers.zammad.rule: Host(${SERVICES_ZAMMAD_LABELS_TRAEFIK_HOST})
      traefik.http.services.zammad.loadbalancer.server.port: "8080"
      com.centurylinklabs.watchtower.enable: true
    networks:
      default: null
      proxy: null

  zammad-postgresql:
    image: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
    labels:
      com.centurylinklabs.watchtower.enable: true

  zammad-railsserver:
    labels:
      com.centurylinklabs.watchtower.enable: true

  zammad-redis:
    labels:
      com.centurylinklabs.watchtower.enable: true

  zammad-scheduler:
    labels:
      com.centurylinklabs.watchtower.enable: true

  zammad-websocket:
    labels:
      com.centurylinklabs.watchtower.enable: true

networks:
  default:
  proxy:
    external: true
