name: Secret Scan on Push, Pull request

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        # Only scan working tree
        with:
          args: "--no-git -v"
