name: Secret Scan

on: [push, pull_request]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit and detect-secrets
        run: |
          pip install pre-commit detect-secrets
          pre-commit install-hooks

      - name: Run pre-commit checks
        run: pre-commit run --all-files
